In [1]:
import numpy as np
numbers=np.array([4,6,9.5])
numbers

array([4. , 6. , 9.5])

In [ ]:
conda install -c plotly plotly

In [3]:
numbers2=np.array([[1,2,3],[4,5,6]])
numbers2

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
numbers3=np.array([[2,'d',4],[4,'g',6]])
numbers3

array([['2', 'd', '4'],
       ['4', 'g', '6']], dtype='<U11')

In [8]:
evens=np.array([2*i for i in range(1,11)])
evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [10]:
evens = np.array([x for x in range(2,21,2)])
evens

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [11]:
three = np.array([[x for x in range(2,11,2)],[y for y in range(1,10,2)]])
three

array([[ 2,  4,  6,  8, 10],
       [ 1,  3,  5,  7,  9]])

In [12]:
three.ndim

2

In [13]:
three.shape

(2, 5)

In [14]:
three.size

10

In [15]:
three.itemsize

4

In [18]:
for rows in three:
    for number in rows:
        print(number, end=' ')
    print()

2 4 6 8 10 
1 3 5 7 9 


In [19]:
for item in three.flat:
    print(item, end=' ')

2 4 6 8 10 1 3 5 7 9 

In [23]:
np.zeros(5, dtype=int)

array([0, 0, 0, 0, 0])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [28]:
np.full((2,3), 6, dtype=float)

array([[6., 6., 6.],
       [6., 6., 6.]])

In [29]:
test1=np.array([1,2,3.])
test1

array([1., 2., 3.])

In [30]:
test1.dtype

dtype('float64')

In [31]:
test2=np.arange(5,10,2)
test2

array([5, 7, 9])

In [3]:
test3=np.linspace(0,1)
test3

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [34]:
test4=np.linspace(0,1,num=3)
test4

array([0. , 0.5, 1. ])

In [39]:
test4=np.arange(0,20000).reshape(20,1000)
test4

array([[    0,     1,     2, ...,   997,   998,   999],
       [ 1000,  1001,  1002, ...,  1997,  1998,  1999],
       [ 2000,  2001,  2002, ...,  2997,  2998,  2999],
       ...,
       [17000, 17001, 17002, ..., 17997, 17998, 17999],
       [18000, 18001, 18002, ..., 18997, 18998, 18999],
       [19000, 19001, 19002, ..., 19997, 19998, 19999]])

In [40]:
test5=np.arange(2,41,2).reshape(4,5)
test5

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20],
       [22, 24, 26, 28, 30],
       [32, 34, 36, 38, 40]])

In [47]:
import random
%timeit die1=[random.randrange(1,7) for i in range(0,6_000_000)]


62 µs ± 541 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [48]:
%timeit die2=np.random.randint(1,7,6_000_000)

44.3 ms ± 428 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [6]:
sum([i for i in range (0,10_000_000)])


49999995000000

In [17]:
import numpy as np
w= np.arange(10_000_000)
w
w.sum()

-2014260032

In [64]:
w=2147483647+1
w

2147483648

In [65]:
w=2147483647^2
w

2147483645

In [66]:
w=2147483647**2
w

4611686014132420609

In [3]:
w=2147483647
w

2147483647

In [5]:
s=0
for i in range(10_000_000):
    s+=i
s

49999995000000

In [18]:
a=np.arange(5)
a

array([0, 1, 2, 3, 4])

In [19]:
a**2

array([ 0,  1,  4,  9, 16], dtype=int32)

In [20]:
a*2

array([0, 2, 4, 6, 8])

In [21]:
b=np.random.randint(1,7,5)
b

array([5, 2, 5, 1, 3])

In [30]:
c=np.full((2,3), 4)

d=np.full((1,2),5)

c-d

ValueError: operands could not be broadcast together with shapes (2,3) (1,2) 

In [31]:
numbers=np.arange(5)
numbers

array([0, 1, 2, 3, 4])

In [32]:
numbers2=np.linspace(1.1,5.5, 5)
numbers2

array([1.1, 2.2, 3.3, 4.4, 5.5])

In [33]:
numbers+numbers2

array([1.1, 3.2, 5.3, 7.4, 9.5])

In [35]:
numbers >=numbers2

array([False, False, False, False, False])

In [37]:
grades=np.random.randint(60,100, 20)
grades

array([63, 62, 69, 91, 88, 64, 83, 64, 63, 85, 96, 99, 66, 95, 60, 68, 67,
       65, 90, 88])

In [38]:
type(grades)

numpy.ndarray

In [41]:
grades.dtype


dtype('int32')

In [48]:
grades=np.random.randint(60,100, 20)
grades.sum()

1518

In [5]:
import numpy as np
array=np.random.randint(60,101, 12).reshape((3,4))
print(array)
print(array.mean())
print('row mean is ', np.mean(array,axis=1))
print('column mean is ', np.mean(array,axis=0))




[[ 93  61  84  88]
 [ 61  72  64 100]
 [ 79  85  79  78]]
78.66666666666667
row mean is  [81.5  74.25 80.25]
column mean is  [77.66666667 72.66666667 75.66666667 88.66666667]


In [6]:
a=np.arange(1,6,1)
a

array([1, 2, 3, 4, 5])

In [8]:
b=np.power(a,3)
b

array([  1,   8,  27,  64, 125], dtype=int32)

In [1]:
if 1:
print('hi')

IndentationError: expected an indented block (<ipython-input-1-5c83aa4e4248>, line 2)

In [4]:
import numpy as np
a=np.arange(1,16).reshape(3,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
a[[0,2]]

array([[ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15]])

In [16]:
a[:,0]

array([ 1,  6, 11])

In [17]:
a[:,1:4]

array([[ 2,  3,  4],
       [ 7,  8,  9],
       [12, 13, 14]])

In [18]:
a=np.array([1,2,3])
a

array([1, 2, 3])

In [19]:
b=a
b


array([1, 2, 3])

In [20]:
a=np.array([4,5])
b, a

(array([1, 2, 3]), array([4, 5]))

In [21]:
b=a.view()
b

array([4, 5])

In [22]:
a=np.array([1,2,3])
a


array([1, 2, 3])

In [23]:
b

array([4, 5])

In [30]:
a=np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [31]:
b=a.view()
b

array([1, 2, 3, 4, 5])

In [32]:
a[1] *= 20
a

array([ 1, 40,  3,  4,  5])

In [33]:
b

array([ 1, 40,  3,  4,  5])

In [34]:
a[3] +=4
a, b

(array([ 1, 40,  3,  8,  5]), array([ 1, 40,  3,  8,  5]))

In [35]:
a=np.arange(1,7)
a

array([1, 2, 3, 4, 5, 6])

In [36]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [37]:
a

array([1, 2, 3, 4, 5, 6])

In [38]:
a.resize(2,3)
a

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
a= np.arange(1,7)
b=a.reshape(2,3)
a,b

(array([1, 2, 3, 4, 5, 6]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [40]:
b[1,1]=500
b

array([[  1,   2,   3],
       [  4, 500,   6]])

In [41]:
a

array([  1,   2,   3,   4, 500,   6])

In [69]:
a = np.array([[1,2,3],[4,5,6]])
a.reshape (1,6)
b = a.copy()
a, b

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[1, 2, 3],
        [4, 5, 6]]))

In [70]:
a[0,1]=30000
b,a

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[    1, 30000,     3],
        [    4,     5,     6]]))

In [58]:
b

array([[1, 2, 3, 4, 5, 6]])

In [75]:
c=np.array([2,3,4,5])
c

array([2, 3, 4, 5])

In [76]:
d=c
c,d

(array([2, 3, 4, 5]), array([2, 3, 4, 5]))

In [78]:
c=np.array([1,20])
d,c

(array([2, 3, 4, 5]), array([ 1, 20]))

In [ ]:
jasdhg

In [1]:
pip install autopep8

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np
a=np.arange(60_000_000)
a

array([       0,        1,        2, ..., 59999997, 59999998, 59999999])

In [4]:
import numpy as np
grade1=np.arange(1,7).reshape(2,3)
grade1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
grade2=np.hstack((grade1,grade1))
grade3=np.vstack((grade2,grade2))
grade3

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [6]:
import pandas as pd
test=pd.Series([2,3,4.])
test[2]

4.0

In [13]:
import numpy as np
import pandas as pd
test=pd.Series(10.1, [2,3,4])
test

2    10.1
3    10.1
4    10.1
dtype: float64

In [1]:
import pandas as pd
test=pd.Series((5,7, 10))
test


0     5
1     7
2    10
dtype: int64

In [2]:
import pandas as pd
test=pd.Series([5,7, 10])
test

0     5
1     7
2    10
dtype: int64

In [3]:
import pandas as pd
test=pd.Series(2.5, index = range(4))

In [4]:
test

0    2.5
1    2.5
2    2.5
3    2.5
dtype: float64

In [6]:
import pandas as pd
student_grades = pd.Series([85, 95, 90, 100], index = ['Anna', 'John', 'Milo', 'Yasmin'])
student_grades

Anna       85
John       95
Milo       90
Yasmin    100
dtype: int64

In [7]:
import pandas as pd
studentGrades = pd.Series([85, 95, 90, 100], index = ['Anna', 'John', 'Milo', 'Yasmin'])
studentGrades.values


array([ 85,  95,  90, 100], dtype=int64)

In [8]:
import pandas as pd
studentGrades = pd.Series([85, 95, 90, 100], index = ['Anna', 'John', 'Milo', 'Yasmin'])
studentGrades.index


Index(['Anna', 'John', 'Milo', 'Yasmin'], dtype='object')

In [9]:
import pandas as pd
studentGrades = pd.Series([85, 95, 90, 100], index = ['Anna', 'John', 'Milo', 'Yasmin'])
studentGrades.index


Index(['Anna', 'John', 'Milo', 'Yasmin'], dtype='object')

In [11]:
import pandas as pd
studentGrades = pd.Series([85, 95, 90, 100], index = ['Anna', 'John', 'Milo', 'Yasmin'])
studentGrades.values


array([ 85,  95,  90, 100], dtype=int64)

In [12]:
import pandas as pd
studentGrades = pd.Series([85, 95, 90, 100], index = ['Anna', 'John', 'Milo', 'Yasmin'])
studentGrades['Milo']

90

In [13]:
d = {'Anna':85, 'John':95, 'Milo':90, 'Yasmin':100}
studentGrades = pd.Series(d)
studentGrades


Anna       85
John       95
Milo       90
Yasmin    100
dtype: int64

In [2]:
x=10
y=20
sum = x + y
average = sum / 2
print(sum)

30


In [3]:
grade = float(input('Enter a grade'))
print('Pass') if grade >= 70 else print('fail')

Enter a grade 55


fail


In [1]:
import numpy as np
import pandas as pd

%load_ext lab_black

In [2]:
2 + 3

5

In [1]:
2+3

5